#!/usr/bin/env bash
# Collect read-only HDMI RX, EDID, RGA, and RKMPP baseline information.
set -u

readonly PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly DEFAULT_OUTPUT="$PROJECT_DIR/docs/rkmpp/diagnostics/stage-0-baseline-$(date +%Y%m%d).md"
readonly OUTPUT="${1:-$DEFAULT_OUTPUT}"
readonly VIDEO_DEVICE="${VIDEO_DEVICE:-/dev/video0}"

mkdir -p "$(dirname "$OUTPUT")"

section() {
  printf '\n## %s\n\n' "$1"
}

run_capture() {
  local label="$1"
  shift
  printf '### %s\n\n' "$label"
  printf '\$'
  printf ' %q' "$@"
  printf '\n\n'
  local output
  local status
  output=$("$@" 2>&1)
  status=$?
  # V4L2 tools use tabs/spaces to pad otherwise empty fields.  Strip only
  # trailing horizontal whitespace so Markdown remains diff --check clean.
  output=$(printf '%s\n' "$output" | sed -E 's/[[:space:]]+$//')
  if [[ -n "$output" ]]; then
    printf '```text\n%s\n```\n\n' "$output"
  else
    printf '```text\n(no output)\n```\n\n'
  fi
  printf 'Exit status: `%d`\n\n' "$status"
}

run_shell_capture() {
  local label="$1"
  local command="$2"
  shift 2
  printf '### %s\n\n' "$label"
  printf '\$ %s\n\n' "$command"
  local output
  local status
  output=$(bash -c "$command" run_shell_capture "$@" 2>&1)
  status=$?
  output=$(printf '%s\n' "$output" | sed -E 's/[[:space:]]+$//')
  if [[ -n "$output" ]]; then
    printf '```text\n%s\n```\n\n' "$output"
  else
    printf '```text\n(no output)\n```\n\n'
  fi
  printf 'Exit status: `%d`\n\n' "$status"
}

append_no_index_whitespace_check() {
  local path="$1"
  local diagnostics
  local status
  diagnostics=$(git -C "$PROJECT_DIR" diff --no-index --check /dev/null "$path" 2>&1)
  status=$?
  if [[ -z "$diagnostics" && "$status" -eq 1 ]]; then
    printf -- '- `%s`: **PASS** (exit 1 is expected for a differing file; no whitespace diagnostics).\n' "$path"
  else
    printf -- '- `%s`: **FAIL** (exit %d).\n' "$path" "$status"
    if [[ -n "$diagnostics" ]]; then
      printf '```text\n%s\n```\n' "$diagnostics"
    fi
  fi
}

{
  printf '# Stage 0 RKMPP/HDMI RX capability probe\n\n'
  printf '> This report is generated by `scripts/rkmpp_stage0_probe.sh`. The probe is read-only: it never invokes `VIDIOC_S_EDID`, `--set-edid`, `--clear-edid`, or `VIDIOC_S_FMT`.\n\n'
  printf -- '- Generated at: `%s`\n' "$(date --iso-8601=seconds)"
  printf -- '- Host: `%s`\n' "$(hostname)"
  printf -- '- Video device: `%s`\n' "$VIDEO_DEVICE"

  section "Environment and repository"
  run_capture "Kernel and architecture" uname -a
  run_capture "OS release" bash -c 'sed -n "1,80p" /etc/os-release'
  run_capture "Repository revision" git -C "$PROJECT_DIR" rev-parse HEAD
  run_capture "Repository status" git -C "$PROJECT_DIR" status --short
  run_capture "Relevant build cache directories" bash -c 'find "$1" -maxdepth 1 -mindepth 1 -type d \( -name "build-*" -o -name "cmake-build-*" \) -printf "%f\n" | sort' _ "$PROJECT_DIR"

  section "Required command availability"
  for command_name in v4l2-ctl media-ctl edid-decode pkg-config cmake ffprobe ffmpeg; do
    if command -v "$command_name" >/dev/null 2>&1; then
      run_capture "$command_name version" "$command_name" --version
    else
      printf -- '- `%s`: **MISSING**\n\n' "$command_name"
    fi
  done

  section "V4L2 HDMI RX"
  if [[ -e "$VIDEO_DEVICE" ]]; then
    run_capture "Driver and capabilities" v4l2-ctl -d "$VIDEO_DEVICE" -D
    run_capture "All controls, active timings, and current format" v4l2-ctl -d "$VIDEO_DEVICE" --all
    run_capture "Enumerated capture formats" v4l2-ctl -d "$VIDEO_DEVICE" --list-formats-ext
    run_capture "Current capture format" v4l2-ctl -d "$VIDEO_DEVICE" --get-fmt-video
    run_capture "Active DV timings" v4l2-ctl -d "$VIDEO_DEVICE" --query-dv-timings
    run_capture "Read-only video-node EDID (VIDIOC_G_EDID)" v4l2-ctl -d "$VIDEO_DEVICE" --get-edid
  else
    printf -- '- `%s`: **BLOCKED** (device node does not exist)\n\n' "$VIDEO_DEVICE"
  fi

  section "Media graph and V4L2 sub-devices"
  mapfile -t media_nodes < <(find /dev -maxdepth 1 -type c -name 'media[0-9]*' -printf '%p\n' 2>/dev/null | sort)
  if ((${#media_nodes[@]} == 0)); then
    printf -- '- No `/dev/media*` nodes were present; media graph enumeration is **UNKNOWN**.\n\n'
  else
    for media_node in "${media_nodes[@]}"; do
      run_capture "Media graph $media_node" media-ctl -d "$media_node" -p
    done
  fi
  mapfile -t subdev_nodes < <(find /dev -maxdepth 1 -type c -name 'v4l-subdev[0-9]*' -printf '%p\n' 2>/dev/null | sort)
  if ((${#subdev_nodes[@]} == 0)); then
    printf -- '- No `/dev/v4l-subdev*` nodes were present; sub-device EDID ownership is **UNKNOWN**.\n\n'
  else
    for subdev_node in "${subdev_nodes[@]}"; do
      run_capture "Sub-device capabilities $subdev_node" v4l2-ctl -d "$subdev_node" -D
      run_capture "Read-only sub-device EDID pad 0 ($subdev_node)" v4l2-ctl -d "$subdev_node" --get-edid pad=0
    done
  fi

  section "Device permissions and kernel exposure"
  run_capture "Relevant device nodes" ls -l "$VIDEO_DEVICE" /dev/mpp_service /dev/rga
  run_capture "Current user and groups" id
  run_shell_capture "Video4Linux sysfs links" 'for node in /sys/class/video4linux/*; do [[ -e "$node" ]] || continue; printf "%s name=" "$node"; cat "$node/name" 2>/dev/null; printf " device="; readlink -f "$node/device"; done'
  run_shell_capture "Loaded relevant kernel modules" 'lsmod 2>/dev/null | grep -Ei "rga|mpp|hdmi|v4l2|rockchip" || true'

  section "RKMPP headers, linker, and pkg-config"
  run_capture "RKMPP pkg-config flags" pkg-config --cflags --libs rockchip_mpp
  run_capture "RKMPP pkg-config version" pkg-config --modversion rockchip_mpp
  run_shell_capture "RKMPP headers" 'for header in rk_mpi.h mpp_buffer.h mpp_frame.h; do find /usr/include -name "$header" -print; done'
  run_shell_capture "MPP shared libraries" 'ldconfig -p 2>/dev/null | grep -Ei "rockchip_mpp|mpp" || true'
  run_shell_capture "MPP library files" 'find /usr/lib /lib -type f -o -type l 2>/dev/null | grep -E "/lib(rockchip_mpp|mpp)\.so" | sort -u || true'
  run_shell_capture "CMake RKMPP detection cache" 'for cache in "$1"/build-rkmpp-review/CMakeCache.txt "$1"/build-clang/CMakeCache.txt "$1"/cmake-build-rkmpp/CMakeCache.txt; do [[ -f "$cache" ]] || continue; printf "[%s]\n" "$cache"; grep -E "^(RKMPP_FOUND|RockchipMPP_FOUND|ROCKCHIPMPP_|SUNSHINE_ENABLE_RKMPP)" "$cache" || true; done' "$PROJECT_DIR"

  section "RGA library and headers"
  run_shell_capture "RGA device and shared library" 'ls -l /dev/rga; ldconfig -p 2>/dev/null | grep -Ei "librga" || true'
  run_shell_capture "RGA headers" 'for header in RgaApi.h im2d.h im2d_buffer.h; do find /usr/include -path "*/rga/$header" -print; done'
  run_shell_capture "RGA pkg-config" 'pkg-config --modversion librga 2>&1; pkg-config --cflags --libs librga 2>&1'
  run_shell_capture "RGA exported diagnostic symbols" 'for library in /usr/lib/*/librga.so* /lib/*/librga.so*; do [[ -f "$library" || -L "$library" ]] || continue; printf "[%s]\n" "$library"; nm -D "$library" 2>/dev/null | grep -E "imcheck|imresize|imfill|importbuffer|releasebuffer" || true; done'
  printf 'RGA format operation matrix (BGR3/NV24/NV16/NV12 input -> NV12 output): **UNKNOWN** until a matching librga development header and an executable `imcheck()`/demo probe are available. The installed runtime library alone does not prove format support, so no result is inferred here.\n\n'

  section "Existing Sunshine baseline evidence"
  if [[ -f "$PROJECT_DIR/runtime-home/config/sunshine/sunshine.log" ]]; then
    run_shell_capture "Successful same-resolution session evidence" 'grep -E "CLIENT CONNECTED|Creating encoder \[(h264_rkmpp|hevc_rkmpp)\]|Color coding:|Color depth:|Color range:|CLIENT DISCONNECTED" "$1" | tail -80' "$PROJECT_DIR/runtime-home/config/sunshine/sunshine.log"
    run_shell_capture "Mismatched-resolution failure evidence" 'grep -E "hdmirx dimensions .* do not match requested stream|RKMPP/HDMI RX capture setup failed|Couldn.t find any working encoder matching|Unable to find display or encoder" "$1" | tail -80' "$PROJECT_DIR/runtime-home/config/sunshine/sunshine.log"
  else
    printf -- '- Sunshine runtime log not found; same/mismatched session evidence is **BLOCKED**.\n\n'
  fi
  printf 'The existing log excerpts are historical evidence only; repeatable end-to-end Moonlight runs still require a controlled client and a known HDMI source.\n\n'

  section "Probe interpretation"
  printf -- '- EDID writes: **NOT PERFORMED**.\n'
  printf -- '- V4L2, active timings, and MPP checks above are direct observations from this host.\n'
  printf -- '- Any command with a non-zero exit status, absent node, missing package, or missing header remains **UNKNOWN/BLOCKED** and must not be treated as support.\n'
  printf -- '- RGA `imcheck()`/demo format results are intentionally not guessed when the development headers or a hardware probe are unavailable.\n'

  section "Stage 0 acceptance and hand-off"
  printf '| Check | Result | Evidence or blocker |\n| --- | --- | --- |\n'
  printf '| Same-resolution Moonlight baseline | **PASS (historical)** | Runtime log contains successful `CLIENT CONNECTED` sessions and H.264/HEVC RKMPP encoder creation; exact coded dimensions are not present in the log. |\n'
  printf '| Mismatched-resolution failure chain | **PASS** | Historical log reports `hdmirx dimensions ... do not match requested stream` before RKMPP/session failure. |\n'
  printf '| V4L2 driver/capabilities/formats/format/timings | **PASS** | `/dev/video0` is `rk_hdmirx`; active 1920x1080 progressive 60.00 fps; BGR3/NV24/NV16/NV12 enumerated; current format NV24. |\n'
  printf '| Video-node EDID read | **PASS** | `v4l2-ctl --get-edid` returned two 128-byte blocks; no write was attempted. |\n'
  printf '| Media graph and sub-device EDID ownership | **UNKNOWN** | No `/dev/media*` or `/dev/v4l-subdev*` node was present. |\n'
  printf '| RKMPP headers, link library, and device | **PASS** | Headers, `pkg-config rockchip_mpp` 1.3.9, CMake capability cache, `/dev/mpp_service`, and group permissions are present. |\n'
  printf '| RGA device/runtime and BGR3/NV24/NV16/NV12 → NV12 operations | **PARTIAL / UNKNOWN** | `/dev/rga` and `librga.so.2.1.0` are present, but development headers/pkg-config and an `imcheck()`/demo executable are absent. |\n'
  printf '| Destructive EDID experiment | **NOT RUN (by design)** | Stage 7 requires explicit permission and a recovery plan. |\n\n'
  printf '### Files and ownership\n\n'
  printf -- '- `scripts/rkmpp_stage0_probe.sh`: read-only diagnostic owner; accepts an optional output path and `VIDEO_DEVICE`; never writes EDID, format, or device state.\n'
  printf -- '- `docs/rkmpp/diagnostics/stage-0-baseline-*.md`: generated evidence artifact; rerun the script on the target host rather than hand-editing observations.\n'
  printf -- '- `PLAN.md`: pre-existing untracked user file; intentionally untouched.\n\n'
  printf '### Commands and results\n\n'
  printf -- '- `bash -n scripts/rkmpp_stage0_probe.sh`: **PASS**.\n'
  printf -- '- `scripts/rkmpp_stage0_probe.sh docs/rkmpp/diagnostics/stage-0-baseline-YYYYMMDD.md`: **PASS** on this host; report generated.\n'
  printf -- '- `cmake --build build-rkmpp-review --parallel 2`: **BLOCKED** in the existing cache during the Web UI step because Node.js 18.20.4 lacks `crypto.hash` required by the installed Vite/Vue toolchain; no stage 0 source build was needed.\n'
  printf -- '- V4L2/media/EDID read-only commands in this report: **PASS** for `/dev/video0`; media/sub-device enumeration is **UNKNOWN** because nodes are absent.\n'
  printf -- '- `rkmpp_hdmirx_smoke --frames 300`, `rkmpp_rkmpp_smoke --codec h264|h265`, `ffprobe`, and `ffmpeg`: **NOT RUN/BLOCKED** here because the existing build has no smoke test binaries and ffprobe/ffmpeg are not installed.\n'
  printf -- '- Controlled Moonlight same-resolution/mismatch reruns: **NOT RUN** in this probe; historical Sunshine log evidence is preserved above.\n\n'
  printf '### Branches covered\n\n'
  printf -- '- Covered successful paths: present V4L2 node, active timings, current format, video-node G_EDID, MPP headers/link/device, and readable device permissions.\n'
  printf -- '- Covered failure/fallback paths: missing command, missing device node, failed media enumeration, absent sub-devices, absent RGA development files, and non-zero command status are emitted as **MISSING**, **UNKNOWN**, or **BLOCKED**, never as support.\n\n'
  printf '### Reproduction commands\n\n```bash\n# Read-only complete report (target ROCK 5B+):\nscripts/rkmpp_stage0_probe.sh docs/rkmpp/diagnostics/stage-0-baseline-$(date +%%Y%%m%%d).md\n\n# Optional alternate V4L2 node; still read-only:\nVIDEO_DEVICE=/dev/video1 scripts/rkmpp_stage0_probe.sh /tmp/stage-0-video1.md\n\n# Existing baseline log filters:\nrg -n "hdmirx dimensions|CLIENT CONNECTED|Creating encoder \\[(h264_rkmpp|hevc_rkmpp)\\]" runtime-home/config/sunshine/sunshine.log\n```\n\n'
  printf '### Unknowns that do not block the next strategy stage\n\n'
  printf -- '- RGA operation results for each requested source format are unknown until a matching librga development package and executable hardware probe are available.\n'
  printf -- '- No media-controller graph or sub-device EDID endpoint is exposed in this boot; video-node EDID is readable, but safe write/restore capability is not established.\n'
  printf -- '- Exact encoded coded dimensions and ffprobe decode validation need a controlled Moonlight/codec smoke run with ffprobe/ffmpeg installed.\n'
  printf -- '- These unknowns are intentionally handed to later stages; no scaling or EDID negotiation is implemented here.\n\n'
  printf '### Final repository checks\n\n'
  run_capture "git diff --check (tracked files)" git -C "$PROJECT_DIR" diff --check
  run_capture "git status --short" git -C "$PROJECT_DIR" status --short
  printf -- '- `PLAN.md` remains the pre-existing untracked user file; no files were deleted or cleaned.\n'
} >"$OUTPUT"

{
  printf '\n### Post-generation untracked-file whitespace checks\n\n'
  append_no_index_whitespace_check "$PROJECT_DIR/scripts/rkmpp_stage0_probe.sh"
  append_no_index_whitespace_check "$OUTPUT"
} >>"$OUTPUT"

printf 'Wrote %s\n' "$OUTPUT"
